#!/bin/bash

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

ROOT_DIR=$(pwd)

folders=("configs" "data" "dataloader" "executor" "models" "ops" "output" "output/plots" "output/plots/bar_plots" "output/plots/choropleth" "output/plots/count_plots" "output/plots/decision_trees" "output/plots/heatmaps" "output/plots/histograms" "output/plots/neural_network" "output/plots/pair_plots" "output/plots/residuals" "output/plots/word_clouds" "output/processing_steps" "utils")
files=("support_vector_machine_project.py" "spotify_test.csv" "spotify_train.csv" "setup.py" "plotter.py" "neural_network.py" "grid_search_output.txt" "dataloader.py" "config.py" "support_vector_machine.py" "api_caller.py" "evaluator.py")

# Create Project Folders
function create_folders() {
   folder_list=("$@")
   for folder in "${folder_list[@]}";
      do
          if [ ! -d "$ROOT_DIR/$folder" ] ; then
            echo -e "${GREEN}Creating Project Folder $folder\n${NC}"
            mkdir "$folder"
          fi
      done
}

# Move Source Files to Project Folders
function move_files_to_folder() {
   file_list=("$@")
   for file in "${file_list[@]}";
      do
        if test -f "$ROOT_DIR/$file"; then

          case $file in

            "support_vector_machine_project.py")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}executor\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/executor/$file"
              ;;

            "spotify_test.csv" | "spotify_train.csv")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}data\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/data/$file"
              ;;

            "config.py")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}configs\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/configs/$file"
              ;;

            "setup.py")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}utils\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/utils/$file"
              ;;

            "plotter.py" | "api_caller.py" | "evaluator.py")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}ops\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/ops/$file"
              ;;

            "neural_network.py" | "support_vector_machine.py")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}models\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/models/$file"
              ;;

            "grid_search_output.txt")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}output\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/output/$file"
              ;;

            "dataloader.py")
              echo -e "${GREEN}Moving ${NC}$file${GREEN} to Project Folder ${NC}dataloader\n"
              mv "$ROOT_DIR/$file" "$ROOT_DIR/dataloader/$file"
              ;;
          esac
        fi
      done
}

# Check for existence of Virtual Environment
function check_for_virtual_environment() {
    if [ ! -d "$ROOT_DIR/venv" ] ; then

      # If not found create one
      echo -e "${GREEN}Creating Virtual Environment\n${NC}"
      python -m venv venv

      else
        # If it exists inform the user
        echo -e "${GREEN}Found existing Virtual Environment\n${NC}"

    fi
}

# Activate Virtual Environment
function activate_virtual_environment() {
    echo -e "${GREEN}Activating Virtual Environment\n${NC}"
    source "$ROOT_DIR/venv/bin/activate"
}

# Get current Virtual Environment name
function get_virtual_environment() {
    echo -e "${GREEN}Current Virtual Environment\n${NC}"
    echo "$VIRTUAL_ENV"
}

# Run the setup.py script
function run_setup() {
    echo -e "${GREEN}\nRunning setup.py\n${NC}"
    python "$ROOT_DIR/utils/setup.py" "$ROOT_DIR"
}

# Run the whole project
function run() {
	if [ "$#" -eq 0 ]; then
		create_folders "${folders[@]}"
        move_files_to_folder "${files[@]}"
        check_for_virtual_environment
        activate_virtual_environment
        get_virtual_environment
        run_setup
		else
		  echo -e "${RED}Too many arguments!\n${NC}"
  	fi
}

run "$@"
